# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Customers name to use as alt_text for the logo', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, help_text='If present the logo will link here', max_length=2000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='customers_heading',
            field=models.CharField(default='Customers', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_heading',
            field=models.CharField(default='Features', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials_heading',
            field=models.CharField(default='Testimonials', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='href',
            field=models.CharField(blank=True, help_text='A link to the finished project (optional)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='col1_heading',
            field=models.CharField(default='About us', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='col2_heading',
            field=models.CharField(default='Useful links', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='col3_heading',
            field=models.CharField(default='Follow us on Twitter', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='col3_widget',
            field=models.TextField(help_text='This is a great place to put something like a twitter widget'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='col4_heading',
            field=models.CharField(default='From the Blog', max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_icon',
            field=models.CharField(blank=True, help_text='Name of font awesome 4.0 icon (i.e. fa-arrows). A list of icons is at http://fontawesome.io/icons/', max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_alignment',
            field=models.CharField(choices=[('LE', 'Image on left (600x363)'), ('RI', 'Image on right (640x363'), ('NO', 'No image')], default='LE', max_length=2),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(help_text='Feel free to include html'),
        ),
    ]
